<?php
require_once __DIR__ . '/includes/cart_helpers.php';
require_once dirname(__DIR__) . '/Admin/config/database.php';
$userId = nam_cart_current_user_id();
if (!$userId) { nam_cart_flash('Vui lòng đăng nhập để xem đơn hàng.', 'error'); nam_cart_redirect('login.php'); }
$statement = $conn->prepare('SELECT id, order_code, total, status, payment_status, created_at FROM orders WHERE user_id = ? ORDER BY id DESC');
$statement->bind_param('i', $userId); $statement->execute(); $orders = $statement->get_result()->fetch_all(MYSQLI_ASSOC);
$notice = nam_cart_flash(); require __DIR__ . '/includes/header.php';
?>
<style>.nam-orders{max-width:1000px;margin:36px auto;padding:0 20px}.nam-box{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:20px}.nam-table{width:100%;border-collapse:collapse}.nam-table th,.nam-table td{padding:13px 10px;border-bottom:1px solid #eee;text-align:left}.nam-badge{display:inline-block;padding:5px 9px;border-radius:999px;background:#fef3c7;color:#92400e;font-size:12px}.nam-badge.confirmed,.nam-badge.shipping{background:#dbeafe;color:#1d4ed8}.nam-badge.delivered,.nam-badge.success{background:#dcfce7;color:#166534}.nam-badge.cancelled{background:#fee2e2;color:#b91c1c}.nam-btn{display:inline-block;padding:8px 11px;border-radius:7px;background:#111827;color:#fff;text-decoration:none}.nam-alert{padding:12px;border-radius:8px;margin:14px 0}.nam-alert.success{background:#dcfce7}.nam-alert.error{background:#fee2e2}@media(max-width:650px){.nam-table{font-size:13px}.nam-table th:nth-child(3),.nam-table td:nth-child(3){display:none}}</style>
<section class="nam-orders"><h1>Đơn hàng của tôi</h1><?php if($notice):?><div class="nam-alert <?= nam_cart_e($notice['type']) ?>"><?= nam_cart_e($notice['message']) ?></div><?php endif; ?><div class="nam-box"><table class="nam-table"><thead><tr><th>Mã đơn</th><th>Ngày đặt</th><th>Tổng tiền</th><th>Trạng thái</th><th></th></tr></thead><tbody><?php foreach($orders as $order):?><tr><td><strong><?= nam_cart_e($order['order_code']) ?></strong></td><td><?= date('d/m/Y H:i',strtotime($order['created_at'])) ?></td><td><?= nam_cart_money($order['total']) ?></td><td><span class="nam-badge <?= nam_cart_e($order['status']) ?>"><?= nam_cart_e(nam_cart_order_status_text($order['status'])) ?></span></td><td><a class="nam-btn" href="order_detail.php?id=<?= (int)$order['id'] ?>">Chi tiết</a></td></tr><?php endforeach;?><?php if(!$orders):?><tr><td colspan="5">Bạn chưa có đơn hàng nào.</td></tr><?php endif;?></tbody></table></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
