<?php
require_once __DIR__ . '/includes/cart_helpers.php';
require_once dirname(__DIR__) . '/Admin/config/database.php';
$orderId = (int) ($_GET['id'] ?? 0);
$userId = nam_cart_current_user_id();
if (!$userId || $orderId <= 0) { nam_cart_redirect('orders.php'); }
$statement = $conn->prepare('SELECT * FROM orders WHERE id = ? AND user_id = ?');
$statement->bind_param('ii', $orderId, $userId); $statement->execute(); $order = $statement->get_result()->fetch_assoc();
if (!$order) { http_response_code(404); exit('Không tìm thấy đơn hàng.'); }
$statement = $conn->prepare('SELECT * FROM order_items WHERE order_id = ?');
$statement->bind_param('i', $orderId); $statement->execute(); $items = $statement->get_result()->fetch_all(MYSQLI_ASSOC);
$notice = nam_cart_flash(); require __DIR__ . '/includes/header.php';
?>
<style>.nam-detail{max-width:1000px;margin:36px auto;padding:0 20px}.nam-card{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:20px;margin-bottom:18px}.nam-info{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.nam-info small{display:block;color:#6b7280;margin-bottom:3px}.nam-table{width:100%;border-collapse:collapse}.nam-table th,.nam-table td{border-bottom:1px solid #eee;padding:12px 8px;text-align:left}.nam-status{display:inline-block;background:#fef3c7;color:#92400e;border-radius:999px;padding:5px 9px;font-size:12px}.nam-status.confirmed,.nam-status.shipping{background:#dbeafe;color:#1d4ed8}.nam-status.delivered,.nam-status.success{background:#dcfce7;color:#166534}.nam-status.cancelled{background:#fee2e2;color:#b91c1c}.nam-btn{border:0;border-radius:8px;padding:10px 13px;background:#111827;color:#fff;font-weight:600;cursor:pointer}.nam-btn.danger{background:#b91c1c}.nam-alert{padding:12px;border-radius:8px;margin:12px 0}.nam-alert.success{background:#dcfce7}.nam-alert.error{background:#fee2e2}@media(max-width:650px){.nam-info{grid-template-columns:1fr}}</style>
<section class="nam-detail"><p><a href="orders.php">← Đơn hàng của tôi</a></p><h1>Đơn <?= nam_cart_e($order['order_code']) ?></h1><?php if($notice):?><div class="nam-alert <?= nam_cart_e($notice['type']) ?>"><?= nam_cart_e($notice['message']) ?></div><?php endif;?><div class="nam-card"><div class="nam-info"><div><small>Trạng thái</small><span class="nam-status <?= nam_cart_e($order['status']) ?>"><?= nam_cart_e(nam_cart_order_status_text($order['status'])) ?></span></div><div><small>Ngày đặt</small><?= date('d/m/Y H:i',strtotime($order['created_at'])) ?></div><div><small>Người nhận</small><?= nam_cart_e($order['customer_name']) ?> · <?= nam_cart_e($order['phone']) ?></div><div><small>Địa chỉ</small><?= nam_cart_e($order['address']) ?></div></div></div><div class="nam-card"><h2>Sản phẩm</h2><table class="nam-table"><thead><tr><th>Sản phẩm</th><th>Đơn giá</th><th>SL</th><th>Thành tiền</th></tr></thead><tbody><?php foreach($items as $item):?><tr><td><strong><?= nam_cart_e($item['product_name']) ?></strong><br><small><?= nam_cart_e($item['variant_label']) ?></small></td><td><?= nam_cart_money($item['price']) ?></td><td><?= (int)$item['quantity'] ?></td><td><?= nam_cart_money($item['price']*$item['quantity']) ?></td></tr><?php endforeach;?></tbody></table><p style="text-align:right;font-size:19px"><strong>Tổng thanh toán: <?= nam_cart_money($order['total']) ?></strong></p></div><?php if($order['status']==='pending'):?><form method="post" action="cancel_order.php" onsubmit="return confirm('Bạn có chắc muốn hủy đơn hàng này?')"><?= nam_cart_csrf_input() ?><input type="hidden" name="order_id" value="<?= (int)$order['id'] ?>"><button class="nam-btn danger">Hủy đơn hàng</button></form><?php endif;?></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
