<?php
require_once dirname(__DIR__) . '/config/bootstrap.php';
require_once dirname(__DIR__) . '/models/OrderModel.php';
if (function_exists('require_admin')) { require_admin('login.php'); }
elseif (empty($_SESSION['admin_id']) || ($_SESSION['admin_role'] ?? '') !== 'admin') { header('Location: login.php'); exit; }
function nam_admin_order_e(?string $value): string { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function nam_admin_order_money(float|int|string $value): string { return number_format((float)$value, 0, ',', '.') . ' đ'; }
$filters = ['keyword' => trim($_GET['keyword'] ?? ''), 'status' => $_GET['status'] ?? ''];
$model = new OrderModel($conn); $orders = $model->all($filters);
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quản lý đơn hàng</title><link rel="stylesheet" href="../assets/css/style.css"></head><body><main class="page" style="max-width:1300px;margin:auto"><div class="page-head"><div><h2>Quản lý đơn hàng</h2><p>Theo dõi và xử lý trạng thái đơn hàng.</p></div><a class="btn btn-secondary" href="../../Client/index.php">Xem cửa hàng</a></div><section class="card"><form class="filters compact" method="get"><input name="keyword" placeholder="Mã đơn, khách hàng, số điện thoại" value="<?= nam_admin_order_e($filters['keyword']) ?>"><select name="status"><option value="">Tất cả trạng thái</option><?php foreach($model->statuses() as $status):?><option value="<?= $status ?>" <?= $filters['status']===$status?'selected':'' ?>><?= nam_admin_order_e($model->statusText($status)) ?></option><?php endforeach;?></select><button class="btn btn-primary">Lọc đơn hàng</button></form><div class="table-wrap"><table class="data-table"><thead><tr><th>Mã đơn</th><th>Khách hàng</th><th>Sản phẩm</th><th>Tổng tiền</th><th>Thanh toán</th><th>Trạng thái</th><th>Ngày đặt</th><th></th></tr></thead><tbody><?php foreach($orders as $order):?><tr><td><strong><?= nam_admin_order_e($order['order_code']) ?></strong></td><td><?= nam_admin_order_e($order['customer_name']) ?><br><small class="text-muted"><?= nam_admin_order_e($order['phone']) ?></small></td><td><?= (int)$order['item_count'] ?> sản phẩm</td><td><?= nam_admin_order_money($order['total']) ?></td><td><span class="badge <?= nam_admin_order_e($order['payment_status']) ?>"><?= $order['payment_status']==='paid'?'Đã thanh toán':'Chưa thanh toán' ?></span></td><td><span class="badge <?= nam_admin_order_e($order['status']) ?>"><?= nam_admin_order_e($model->statusText($order['status'])) ?></span></td><td class="nowrap"><?= date('d/m/Y H:i',strtotime($order['created_at'])) ?></td><td><a class="btn btn-sm btn-secondary" href="order_detail.php?id=<?= (int)$order['id'] ?>">Chi tiết</a></td></tr><?php endforeach;?><?php if(!$orders):?><tr><td class="empty" colspan="8">Không có đơn hàng phù hợp.</td></tr><?php endif;?></tbody></table></div></section></main></body></html>
